title: Nuva Lab # Shown in header on pages with full_logo: true

url: "https://nuvalab.ai"

defaults:
  -
    scope:
      path: _posts
    values:
      comments: true

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: true
  profile: false
  startings: [html, head, body]
